### ISSUE TITLE
Cassandra client start an internal Solandra server

### ISSUE THREAD

**Issue by rsinelle** [Impetus/kundera#10]
Hi all,

I open a issue because I doesn't understand why a JPA driver need to start a Solandra server in order to connect to cassandra. 
Actually your driver is not for cassandra but for Solandra (internal use).

This "feature" makes this client unusable for common use :store data into cassandra.

Can you explain me your point of view ?

Thanks
Richard

**Comment by mevivs** [comment]
Hi,
Actually it does not start anything like solandra "server". it is minimal use of solandra just to store indexes into cassandra schema. Using solandra instance to create that schema. But it does not start any inbuilt jetty or any other server.

This feature is useful because it helps you to execute:
1) JPAQL(select \* queries)
2) Search within super column values via executing sql queries.(Unique feature).

Hope it helps.

Thanks,
Vivek

**Comment by mevivs** [comment]
Hi Richard,
Should i close this issue?

Vivek

**Comment by mevivs** [comment]
This is not a case anymore. Solandra is moved out now.
