### ISSUE TITLE
Support for ORDER BY CLAUSE in cassandra

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#128]

**Comment by sachur** [comment]
Any solution to use ORDER BY?

Thanks

**Comment by mevivs** [comment]
Not yet. We will analyze if it is possible with 2.4 release.

-Vivek

**Comment by pires** [comment]
Any updates?

**Comment by pires** [comment]
Am I wrong to assume this is only possible with some ordered partitioner (Random won't work) + CQL support + composite key (AFAIK, Cassandra only supports ORDER by composite keys, which depends on ComparatorType)?

**Comment by mevivs** [comment]
Absolutely correct. But need to be analyzed for other databases as well except MongoDB(already supported in mongodb).

-Vivek

**Comment by mevivs** [comment]
Enabled in current trunk. Releasing with 2.8

**Comment by pires** [comment]
Awesome! What are the constraints to use this? Can you point me examples or documentation?

**Comment by chhavigangwal** [comment]
As per the Cassandra the order by clause is currently supported on following :
- if the table has been defined without any specific CLUSTERING ORDER, then then allowed orderings are the order induced by the clustering key and the reverse of that one.
- otherwise, the orderings allowed are the order of the CLUSTERING ORDER option and the reversed one.

A junit with sample test case:
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/src/test/java/com/impetus/client/crud/compositeType/CassandraCompositeTypeTest.java
