### ISSUE TITLE
Kundera 2.4 with cassandra 1.1.5

### ISSUE THREAD

**Issue by eld0** [Impetus/kundera#220]
Hi,
I have no chance to upgrade to latest version of cassandra, I can use only 1.1.5 version. I have a code which successfully work with 1.2.x versions but when I try to start it on a 1.1.5, it always produce following error:

``` java
com.impetus.kundera.KunderaException: org.apache.thrift.TApplicationException: Invalid method name: 'execute_cql3_query'
    at com.impetus.client.cassandra.pelops.PelopsClient.onPersist(PelopsClient.java:449)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:86)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:183)
    at com.impetus.kundera.graph.Node.flush(Node.java:525)
    at com.impetus.kundera.persistence.DefaultTransactionResource.onFlush(DefaultTransactionResource.java:89)
    at com.impetus.kundera.persistence.DefaultTransactionResource.onCommit(DefaultTransactionResource.java:75)
    at com.impetus.kundera.persistence.Coordinator.coordinate(Coordinator.java:79)
    at com.impetus.kundera.persistence.KunderaEntityTransaction.onTransaction(KunderaEntityTransaction.java:127)
    at com.impetus.kundera.persistence.KunderaEntityTransaction.commit(KunderaEntityTransaction.java:77)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:513)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:387)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631)
    ...
```

Is there any chance to have a backward compatibilities with 1.1.x cassandras' branch?
It's very important for me. Or please give an advice, about stable kundera version which is ready for using with 1.1 and have the  issue #189 resolved.

Thanks

**Comment by mevivs** [comment]
In case you sacrifice not to execute cql3 queries and do not set CQL3 version or explicitly set to CQL2 version . It should not be a problem.

-Vivek

**Comment by eld0** [comment]
But how I can set CQL2 version using persistence.xml or through Spring? I just tried to persist instance which contains @EmbeddedId . (I'm trying to use composite keys which supported in 1.1 AFAIK)

**Comment by eld0** [comment]
I saw this code example:

``` java
PelopsClient pc = (PelopsClient)clientMap.get("cassandra");
        pc.setCqlVersion(CassandraConstants.CQL_VERSION_3_0);
        pc.setConsistencyLevel(ConsistencyLevel.ALL);
```

But, how I can do that using Spring/persistence.xml file?

**Comment by mevivs** [comment]
Composite columns can only work with CQL3. With 2.3 onwards Kundera has been migrated to Cassandra 1.2.X api , and cassandra 1.2.x is not backward compatible. So i guess to get this working need to revert back 2.4 locally on Cassandra 1.1.X is only solution.

-Vivek

**Comment by mevivs** [comment]
On
``
PelopsClient pc = (PelopsClient)clientMap.get("cassandra");
pc.setCqlVersion(CassandraConstants.CQL_VERSION_3_0);
pc.setConsistencyLevel(ConsistencyLevel.ALL);

```
First, i suggest to change from Pelops to ThriftClient .
This can be done wherever you hold a reference for your entity manager.

-Vivek
```

**Comment by eld0** [comment]
Thanks for your help,
I'll try to check this!
Guys, you are doing a great job!

P.S. Just another question not related to main one. How I can set multiple nodes IPs in :

``` xml
<property name="kundera.nodes" value=""/> 
```

?
P.S.S you can close this issue think solution was found (upgrade or change composite keys with something else)

**Comment by mevivs** [comment]
Thanks! I wish if any workaround would have been possible for this as it is because cassandra 1.2.x is not backward compatible.
On

```
<property name="kundera.nodes" value=""/> 
```

This is what we working on,  add something around "fail over" and "load balancing" part as well. Unfortunately not possible with current release.

-Vivek

**Comment by mevivs** [comment]
BTW, using Kundera for?

-Vivek

**Comment by eld0** [comment]
We are developing a security service which will be used by other services inside internal network. And we are planning to use cassandra with kundera on a production environment.

**Comment by mevivs** [comment]
Great. All the best. Let me know, if need any support from Kundera team

-Vivek

**Comment by xamry** [comment]
I am looking into this problem.

Sincerely,
Amresh

**Comment by eld0** [comment]
Thanks,
I've problem with

``` java
PelopsClient pc = (PelopsClient)clientMap.get("cassandra");
pc.setCqlVersion(CassandraConstants.CQL_VERSION_3_0);
pc.setConsistencyLevel(ConsistencyLevel.ALL);
```

It doesn't work for me. I'm using Spring and I've sent a test project with unit test to Vivek. So, if needed I can sent it to you. You can find more information here #57

**Comment by xamry** [comment]
If you annotate entityManager with @PersistenceContext and inject it using
org.springframework.orm.jpa._LocalContainerEntityManagerFactoryBean_, it
would successfully work.

However, since you are using org.springframework.orm.jpa.*
LocalEntityManagerFactoryBean*, you would have to inject
EntityManagerFactory and create EntityManager from it.

I made these changes in your code and it works for me. Here is modified
code:

package com.test;

import static org.junit.Assert.*;
import static org.junit.Assert.assertNotNull;

import java.util.Map;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnit;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.impetus.kundera.client.Client;

@RunWith(SpringJUnit4ClassRunner.class)
@DirtiesContext(classMode =
DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
@ContextConfiguration(locations = { "classpath:application-context.xml" })
public class TestCQLVersion
{

```
@PersistenceUnit(unitName= "mto_pu")
private EntityManagerFactory emf ;

@Test
public void testCqlVersionSet()
{
    EntityManager entityManager = emf.createEntityManager();
    Map<String, Client> clientMap = (Map<String, Client>)
```

entityManager.getDelegate();
        assertTrue("Map is empty", 0 < clientMap.size());
        assertNotNull("Cassandra client is null", clientMap.get("mto_pu"));
        assertNotNull("Cassandra client by persistence unit name is null",
clientMap.get("mto_pu"));

```
}
```

}

_applicationContext.xml_

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="
http://www.springframework.org/schema/context"
    xmlns:tx="http://www.springframework.org/schema/tx" xmlns:p="
http://www.springframework.org/schema/p"
    xmlns:c="http://www.springframework.org/schema/c" xmlns:util="
http://www.springframework.org/schema/util"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
http://www.springframework.org/schema/beans/spring-beans-3.1.xsd
http://www.springframework.org/schema/tx
http://www.springframework.org/schema/tx/spring-tx-3.1.xsd
http://www.springframework.org/schema/context
http://www.springframework.org/schema/context/spring-context-3.1.xsd
http://www.springframework.org/schema/util
http://www.springframework.org/schema/util/spring-util-3.1.xsd">

```
<context:annotation-config />
<context:component-scan base-package="com.test" />
<tx:annotation-driven transaction-manager="transactionManager" />

<bean
```

class="org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor"
/>

```
<bean id="entityManagerFactory"
    class="org.springframework.orm.jpa.LocalEntityManagerFactoryBean">
    <property name="persistenceUnitName" value="mto_pu" />
</bean>

<bean id="transactionManager"
```

class="org.springframework.orm.jpa.JpaTransactionManager">
        <property name="entityManagerFactory" ref="entityManagerFactory" />
    </bean>

</beans>

**Comment by eld0** [comment]
Thanks a lot! Second case is working for me ,but when I've tried to replace LocalEntityManagerFactoryBean with LocalContainerEntityManagerFactoryBean - nothing changed, clientMap map still null.
Do I need to change something else except replace entity manager factory bean?
Anyway, thanks a lot. You helped me again. :)

**Comment by eld0** [comment]
Found another issue with nativeQuery.

``` java
com.impetus.kundera.property.PropertyAccessException: java.lang.IllegalArgumentException: Can not set java.lang.String field com.test.model.Client.id to org.apache.cassandra.thrift.Column
```

Here is my test (just added it to my mto-test project):

``` java
@RunWith(SpringJUnit4ClassRunner.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
@ContextConfiguration(locations = {"classpath:application-context.xml"})
public class TestNativeQuery {


    @PersistenceContext(unitName= "mto_pu") 
    private EntityManager entityManager;

    @Test
    public void testNativeQuery(){
        Query q = entityManager.createNativeQuery("select * from clients", Client.class);
        List<Client> list = q.getResultList();
        assertNotNull(list);
    }

}
```

Clients column family needs to have a least one record.
I can create new issue if needed.

Thanks,
Taras

**Comment by mevivs** [comment]
Please raise this as a different issue
-Vivek

**Comment by mevivs** [comment]
Configuring LocalContainerEntityManagerFactoryBean would need some more configurations.

i will share it later.

-Vivek

**Comment by mevivs** [comment]
Any update on this issue please?

-Vivek

**Comment by eld0** [comment]
You can close this issue. We have found a workaround. Just not use CQL3 with Cassandra 1.1.
