### ISSUE TITLE
Dynamic schema configuration for enitities from code

### ISSUE THREAD

**Issue by cjaeger** [Impetus/kundera#221]
Hi,

I'm trying to configure the <b>schema for entities dynamically from code</b>.

I created an entity named "Person" (derived from the sample https://github.com/impetus-opensource/Kundera-Examples/wiki/Cross-datastore-persistence-using-Kundera) but WITHOUT setting a schema in the @Table-Annotation -> @Table(name = "PERSON"), because <b>i would like to configure the target datastore</b> <i>(here: MongoDB)</i> <b>for the Person.class dynamically from an external configuration</b>.

While sarching the Kundera-Sources for a sample, i found the "<b>SchemaConfigurationTest</b>" class in the <b>kundera-core</b> tests and so i tried to configure the schema for Person.class for MongoDB and getting an <b>EntityManagerFactory</b> like this:

<pre>
    @SuppressWarnings("unchecked")
    private static EntityManagerFactory createEntityManagerFactory() {
        final String persistenceUnit = "mongodb";
        final Map&lt;String, Object&gt; props = new HashMap&lt;String, Object&gt;();
        props.put(Constants.PERSISTENCE_UNIT_NAME, persistenceUnit);

        final ApplicationMetadata appMetadata = KunderaMetadata.INSTANCE.getApplicationMetadata();
        final PersistenceUnitMetadata puMetadata = new PersistenceUnitMetadata();
        final Properties p = new Properties();
        puMetadata.setPersistenceUnitName(persistenceUnit);
        p.putAll(props);
        puMetadata.setProperties(p);
        final Map&lt;String, PersistenceUnitMetadata&gt; metadata = new HashMap&lt;String, PersistenceUnitMetadata&gt;();
        metadata.put(persistenceUnit, puMetadata);
        appMetadata.addPersistenceUnitMetadata(metadata);

        final Map&lt;String, List&lt;String&gt;&gt; clazzToPu = new HashMap&lt;String, List&lt;String&gt;&gt;();

        final List&lt;String&gt; pus = new ArrayList&lt;String&gt;();
        pus.add(persistenceUnit);

        clazzToPu.put(Person.class.getName(), pus);

        appMetadata.setClazzToPuMap(clazzToPu);

        final EntityMetadata m = new EntityMetadata(Person.class);
        m.setSchema("KunderaTest@" + persistenceUnit);

        final TableProcessor processor = new TableProcessor(null);
        processor.process(Person.class, m);

        m.setPersistenceUnit(persistenceUnit);

        final MetamodelImpl metaModel = new MetamodelImpl();
        metaModel.addEntityMetadata(Person.class, m);
        
        metaModel.assignManagedTypes(appMetadata.getMetaModelBuilder(persistenceUnit).getManagedTypes());
        metaModel.assignEmbeddables(appMetadata.getMetaModelBuilder(persistenceUnit).getEmbeddables());
        metaModel.assignMappedSuperClass(appMetadata.getMetaModelBuilder(persistenceUnit).getMappedSuperClassTypes());

        appMetadata.getMetamodelMap().put(persistenceUnit, metaModel);

        // ???
        return new EntityManagerFactoryImpl(persistenceUnit, props);
    }
</pre>

<b>But this won't work.</b> When I'm trying to persist a Person object, there will be the following messages:

<pre>
2013-03-20 21:43:56,648 [DEBUG - TableProcessor]: Processing @Entity(Person) for Persistence Object.
2013-03-20 21:43:56,670 [INFO  - EntityManagerFactoryImpl]: EntityManagerFactory created for persistence unit : mongodb
2013-03-20 21:43:56,674 [DEBUG - EntityManagerImpl]: Creating EntityManager for persistence unit : mongodb
2013-03-20 21:43:56,685 [INFO  - ClientResolver]: Returning client instance for:mongodb
Exception in thread "main" com.impetus.kundera.client.ClientResolverException:  No client configured for:mongodb
    at com.impetus.kundera.client.ClientResolver.discoverClient(ClientResolver.java:62)
    at com.impetus.kundera.persistence.PersistenceDelegator.loadClient(PersistenceDelegator.java:779)
    at com.impetus.kundera.persistence.EntityManagerImpl.&lt;init&gt;(EntityManagerImpl.java:136)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:183)
    at Test.testReadWrite(Test.java:138)
    at Test.main(Test.java:59)
</pre>

My <b>persistence.xml</b> looks like this:

<pre>
&lt;persistence xmlns="http://java.sun.com/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0"&gt;
    &lt;persistence-unit name="mongodb"&gt;
        &lt;provider&gt;com.impetus.kundera.KunderaPersistence&lt;/provider&gt;
        &lt;properties&gt;
            &lt;property name="kundera.nodes" value="mongodb-server" /&gt;
            &lt;property name="kundera.port" value="27017" /&gt;
            &lt;property name="kundera.keyspace" value="KunderaTest" /&gt;
            &lt;property name="kundera.dialect" value="mongodb" /&gt;
            &lt;property name="kundera.client.lookup.class" value="com.impetus.client.mongodb.MongoDBClientFactory" /&gt;
            &lt;property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider" /&gt;
            &lt;property name="kundera.cache.config.resource" value="/ehcache.xml" /&gt;
            &lt;property name="kundera.ddl.auto.prepare" value="create" /&gt;
        &lt;/properties&gt;
    &lt;/persistence-unit&gt;
&lt;/persistence&gt;
</pre>

As I have no clue for implementing it, <b>any help would be appreciated...</b>

Thanks, Carsten

P.S.: I'm using Kundera 2.4

**Comment by mevivs** [comment]
With any persistence technology, schema name is fixed at the time of creating entity class.

For using different schema names wrt single entity class in different test environments, you can use tweaks:
1. Modify persitence unit into entity metadata programmatically in test case corresponding to that particular environment. 

```
Map<String, Metamodel> metaModels = KunderaMetadata.INSTANCE.getApplicationMetadata().getMetamodelMap();

    EntityMetadata entityMetadata = KunderaMetadataManager.getEntityMetadata(Account.class);
                for (Metamodel m : metaModels.values())
                {
                    entityMetadata = ((MetamodelImpl) m).getEntityMetadataMap().get(Account.class);
                    if (entityMetadata != null)
                    {
                        break;
                    }
                }
   entityMetadata.setPersistenceUnit("kundera_testu_pu");
```
1. Modify schema name in test case corresponding to that environment

```
PersistenceUnitMetadata puMetadata = KunderaMetadata.INSTANCE.getApplicationMetadata()
                        .getPersistenceUnitMetadata("kundera_testu_pu");
String schema = puMetadata.getProperty(PersistenceProperties.KUNDERA_KEYSPACE);
entityMetadata.setSchema(schema);
```

**Comment by xamry** [comment]
Did this workaround solve your needs, Can we close this one?

**Comment by cjaeger** [comment]
No.
The schema should be read from an configuration file and then setted dynamically.
I solved this issue by using reflection. The @Table schema will be setted dynamically.
Kundera sees just the modified runtime class. This works for me...

Thanks.

**Comment by eld0** [comment]
Hi,
Need the same functionality, but your workaround doesn't work for me. 
I always get null at KunderaMetadataManager.getEntityMetadata(MyClass.class) step.
Cassandra 1.1
Kundera 2.4
Spring 3

**Comment by mevivs** [comment]
Hi,
Have a look at:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-tests/src/test/java/com/impetus/kundera/tests/crossdatastore/useraddress/AssociationBase.java 

Method: switchPersistenceUnits()

Kundera-tests is our test package with junits around all sort of data type and association(s). We created a single entity for RDBMS and then dynamically modifying it for multiple databases at runtime(e.g. Cassandra, REDIS etc).

Please refer it. I will try to get a utility method out of it to handle such scnearios for ease of use.

-Vivek

**Comment by eld0** [comment]
Thanks for help.
I've found my issues, I've tried to use @Table annotation without setting schema parameter that's why it was null.

**Comment by nkasvosve** [comment]
I honestly do not understand why Kundera insists on "schema"  attribute in the Table annotation. It just makes the entities not usable with other JPA platforms like Hibernate; well, at least I cannot find a way to easily accomplish that and that's proving to be a challenge for to switch between different providers. Perhaps someone could enlighten me on this one

**Comment by subes** [comment]
You can override the annotation on application bootstrap via reflection on
the class. That is what i do. Ideally introducing a persistence unit
annotation specifically for kundera would help resolve interoperability
issues.
Am 29.08.2013 11:54 schrieb "nkasvosve" notifications@github.com:

**Comment by mevivs** [comment]
@subes 
Thanks. Can you map your thoughts on this in form of a blog to contribute? I can add that as  FAQ/link in Kundera wiki.

Cheers,
-Vivek

**Comment by subes** [comment]
Actually my solution is quite specific to my application bootstrap and differs from the normal way kundera is used, so code samples would not help a lot. But I can explain the procedure I use to do this:
1. When application is started I scan for all entities and evaluate the @Table schema annotation to find the persistence unit associated via the "schema@some_pu" convention of kundera.
2. Then I generate the persistence.xml on the fly with the properties specific to the various persistence units.
   - jdbc data sources are specified by non-jta-datasource and get retrieved by a custom lookup factory in the EntityManagerFactory/PersistenceUnitManager by persistence unit name
   - hibernate/kundera properties are added there properly
   - class elements are used to only have the persistence units manage the classes they are supposed to work with
3. I adjust the @Table annotation via reflection by overriding the annotation in the class itself: (won't work on some security managers; would not be needed if kundera used an additional annotation like @PersistenceUnit("some_pu") instead of relying on the @Table convention)
   - If the properties specify hibernate, I remove the "@some_pu" suffix.
   - If the properties specify kundera and the "@some_pu" suffix is missing, I add the "@default_pu" suffix to the schema.
4. I enhance the classpath via reflection on the system classloader to make it contain the location of the persistence.xml (won't work on some security managers; would not be needed if kundera had a property to specify the location of the persistence.xml)
5. I load up kundera and hibernate via spring according to the persistence.xml

The problem with this is still that each entity can only be used in one persistence unit at runtime. It is not possible to have hibernate and kundera use the same entity class at the same time. With this approach you only get the flexibility to reconfigure your application so depending on the environment the same entity class is either used with hibernate OR kundera.

If kundera decides to drop the @Table schema convention and introduce a @PersistenceUnit("some_pu") annotation (with some better name for it), it would actually become possible to use the same entity class during runtime for hibernate and kundera at the same time.

**Comment by subes** [comment]
@cjaeger you can also use the annotation hack to modify your schema definition on application startup.
Here is a sample for doing it: http://stackoverflow.com/questions/14268981/modify-a-class-definitions-annotation-string-parameter-at-runtime
You can use http://code.google.com/p/reflections/ to do the classpath scanning, or use the spring way: http://www.nofluffjuststuff.com/blog/scott_leberknight/2008/06/just_how_does_spring_do_its_classpath_component_scanning_magic_

_Edit:_
Should have read your response, seems like you already did this 4 months ago :D

**Comment by nkasvosve** [comment]
Here is my proposed solution inside Kundera core:

package com.impetus.kundera.annotations;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Documented
@Target(ElementType.TYPE)
@Inherited
@Retention(RetentionPolicy.RUNTIME)
public @interface EntitySchema {

```
String name();
```

}

...
....
...

package com.impetus.kundera.metadata.processor;
public class TableProcessor extends AbstractEntityFieldProcessor {
...

private <X extends Class, T extends Object> void populateMetadata(
            EntityMetadata metadata, Class<X> clazz, Map puProperties) {
        Table table = clazz.getAnnotation(Table.class);
        // Set Name of persistence object
        metadata.setTableName(table.name());
        // Add named/native query related application metadata.
        addNamedNativeQueryMetadata(clazz);
        // set schema name and persistence unit name (if provided)
        String schemaStr = "";
        // schemaStr = table.schema();

```
    if (clazz.isAnnotationPresent(EntitySchema.class)) {
        EntitySchema schema = clazz.getAnnotation(EntitySchema.class);
        schemaStr = schema.name();
    }
```

...
...
}

USAGE:

@Entity
@EntitySchema(name="KunderaTests@CassandraPUnit")
@Table(name = "my_table")
public class MyTable  {
}

**Comment by subes** [comment]
I dont like that. The jpa table annotation has the schema part already
specified and should be kept as it is. Instead kundera should drop the @pu
convention in the schema declaration and introduce its own
PersistenceUnitName annotation that only contains the persistence unit name.

Though as discussed in a different ticket, both the table schema and the
persistence unit annotations should not be necessary if the persistence.xml
tells via a class element where this entity belongs to. Because in that
case the persistence properties already know which keyspace (=schema) and
persistence unit is to be used for the entity.
Am 03.09.2013 11:47 schrieb "nkasvosve" notifications@github.com:
