### ISSUE TITLE
Cannot persist entity which was prevously deleted

### ISSUE THREAD

**Issue by OleksandrSemenov** [Impetus/kundera#281]
Kundera version: since 2.2
Cassandra version: since 1.1.8

Hi

There are an issue: when using PelopsClientFactory there are no ability to persist entity which was previously deleted(or persist another entity if it has the same key).
No exceptions, but data is not persisted to the CF - select queries return nothing.
When using ThriftClientFactory it is all fine

Thanks and regards,
Oleksandr

**Comment by jinagko** [comment]
same problem~

**Comment by mevivs** [comment]
Currently, in Kundera we have shifted our default client from Pelops to Thrift based on many reasons. Pelops is not keeping up with pace with Cassandra development and that's why we brought custom thrift implementation. So i would suggest you to use ThriftClientFactory as default Cassandra client.  However, i will keep this issue open and will try to find a solution for this in upcoming releases.

-Vivek
