### ISSUE TITLE
Improve Code coverage in kundera-core

### ISSUE THREAD

**Issue by xamry** [Impetus/kundera#308]
Improve Sonar coverage.

**Comment by pires** [comment]
Coverage metrics are somewhat of a false statement that your code is good because you have plenty tests covering it. As we all know, the number of tests or line covered by tests is by no mean the mirror of our code quality or maintainability.

I for one, would love to see more refactoring, comments/documentation and perhaps redesign of some core components (like schema generation). That would really ease the life of other Kundera wannabe contributors, like myself.
