### ISSUE TITLE
Grouping conditionals. 

### ISSUE THREAD

**Issue by kcarlson** [Impetus/kundera#39]
Grouping conditionals is not possible. 

For example:

`select a from TestEntity a`
`where (a.myBoolean = true and a.myInteger = 100)`
`or (a.myBoolean = false and a.myInteger = 0);`

will throw the exception:

```
java.lang.NumberFormatException: For input string: "100)"
```

**Comment by mevivs** [comment]
Cassandra does not support it yet!

**Comment by mevivs** [comment]
Parser needs to enable such grouping condition. But unfortunately none of no sql provide it directly/indirectly!

-Vivek

**Comment by kcarlson** [comment]
I see.

But couldn't certain groupings be broken down and then run as separate queries against the database and then merged accordingly?

I was thinking something like: org.apache.commons.collections.ListUtils for doing merges

**Comment by mevivs** [comment]
It should. that's why parser needs to be enabled for this. But think what would you want from cassandra out of this query?

select a from TestEntity a
where (a.myBoolean = true and a.myInteger = 100)
or (a.myBoolean = false and a.myInteger = 0);

within cassandra:

Execute 2 statements like :

get TestEntity myBoolean = true and myInteger = 100;

and 

get TestEntity myBoolean = false and myInteger = 0

And then prepare set out of these. Definitly it is programatically possible via data manipulation.

But million dollar question is why cassandra is not providing the same by simply enabling "OR" clause and compute the same? I would suggest rather wait to get this done by cassandra. 

Implementation is certainly possible, but might be redundant in near future. 

Wondering if  CQL allow queries using "OR" clause?

-Vivek

**Comment by kcarlson** [comment]
IBad Request: line 1:70 mismatched input 'or' expecting EOF is what I get when trying to use an 'or' in cqlsh

I agree that waiting for cassandra is a good idea. For now workarounds can be implemented at the application level (not in kundera).
