### ISSUE TITLE
ORDER BY and LIMIT

### ISSUE THREAD

**Issue by jmcube** [Impetus/kundera#62]
hi,

i want to get the last value of an insertion, i'm thinking use order by or limit but i have been doing some test and it doesn´t work.
How can i do this?any clue? have you got any query example  for this
Thanks

**Comment by xamry** [comment]
Which database you are working on? Could you please send me your JPA query...

Sorting won't work with Cassandra or HBase since their underlying APIs don't provide support for that.

Regards,
Amresh

---

From: jmcube [reply@reply.github.com]
Sent: Thursday, May 03, 2012 2:27 PM
To: Amresh Singh
Subject: [Kundera] ORDER BY and LIMIT (#62)

hi,

i want to get the last value of an insertion, i'm thinking use order by or limit but i have been doing some test and it doesn´t work.
How can i do this?any clue? have you got any query example  for this
Thanks

---

Reply to this email directly or view it on GitHub:
https://github.com/impetus-opensource/Kundera/issues/62

---

Upcoming webinar: Building a Sentiment Analytics Solution powered by Machine Learning; May 11(10:00am PT). http://lf1.me/F6/bkmrk

Learn about Impetus’ Load Testing & Mobile Test Automation solutions at Star East Virtual Event- http://lf1.me/M6/starvirtual

NOTE: This message may contain information that is confidential, proprietary, privileged or otherwise protected by law. The message is intended solely for the named addressee. If received in error, please destroy and notify the sender. Any use of this email is prohibited when received in error. Impetus does not represent, warrant and/or guarantee, that the integrity of this communication has been maintained nor that the communication is free of errors, virus, interception or interference.

**Comment by jmcube** [comment]
hi, i´m working with cassandra 1.0.9 and my jpa: Query q=em.createQuery("SELECT d FROM User d ORDER BY d.date");
if it doesn´t suport it, how can i do it?or how can i get the last value inserted in user? and i don´t know another way to do it
regards Jm

**Comment by mevivs** [comment]
Currently we do not support ORDER BY on JPA query over cassandra. However to achieve this(this should help you out)

http://cassandra-user-incubator-apache-org.3065146.n2.nabble.com/CQL-Reversed-and-Comparator-reversed-true-td7399914.html

You can write and execute CQL in same way using Kundera. Here is a Example about how to run native CQL in kundera:

https://github.com/impetus-opensource/Kundera/blob/2.0.6/kundera-cassandra/src/test/java/com/impetus/client/persistence/NativeQueryTest.java

-Vivek
