### ISSUE TITLE
javax.ejb.EJBException: java.lang.IllegalArgumentException: is not a column defined in this metadata

### ISSUE THREAD

**Issue by kannuriajay** [Impetus/kundera#661]
Hi,
## In cassandra DB. table, I have

CREATE TABLE experiment_by_lab (
    experiment_id timeuuid,
    status text,
       labid timeuuid,
primary key(labid, experiment_id)
## );

In Experiment.java I have entity class .

@Column(name ="status")
    private String experimentStatus;  
    public String getExperimentStatus() {
        return experimentStatus;
    }
    public void setExperimentStatus(String experimentStatus) {
        this.experimentStatus = experimentStatus;
##     }

In EJB method I wrote : 
public boolean deleteExperiment(Experiment experiment) {
        Experiment experimentLocal = entityManager.find(Experiment.class, experiment);
        if (experimentLocal != null) {
            experimentLocal.setExperimentStatus("DELETED");
            entityManager.merge(experimentLocal);
            return true;
        } else {
            return false;
        }
##     }

When I run below JUNIT test Case I am getting 
        @Test
    @InSequence(3)
    public void testDeleteExperiment() {
        Experiment experiment = new Experiment();
        experiment.setLabId(labId);
        experiment.setExperimentId(experimentId);
        boolean exp = experimentBean.deleteExperiment(experiment);  
        assertNotNull(exp); 
##     }

Even I create the Index for status column in DB.
create index experiment_by_lab_status on experiment_by_lab(status);

when I run the Junit I am getting below exception: can  help me with some solution.

javax.ejb.EJBException: java.lang.IllegalArgumentException: "status" is not a column defined in this metadata

Thanks in Advance,

AjayKumar.

**Comment by chhavigangwal** [comment]
@kannuriajay 

entityManager.find searches specified object for an entity class with the given primary key and not an entire object . Your code

```
Experiment experimentLocal = entityManager.find(Experiment.class, experiment);
```

ideally should be like : 

```
Experiment experimentLocal = entityManager.find(Experiment.class, experimentId);
```

Hope that Helps!
Chhavi

**Comment by chhavigangwal** [comment]
And to add clarify further as the key experiment table in your case is of  composite type, so you need to create an embeddedId and perform search corresponding to the embeddedId object instead of complete experiment object. Sample entity class  :

https://github.com/impetus-opensource/Kundera/blob/273c13342ddd1aceed0cd23504649926ce8fdb84/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/crud/compositeType/CassandraPrimeUser.java

An sample test case : 
https://github.com/impetus-opensource/Kundera/blob/273c13342ddd1aceed0cd23504649926ce8fdb84/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/crud/compositeType/CassandraCompositeTypeTest.java

Hope that Helps!
Chhavi

**Comment by kannuriajay** [comment]
Hi, 

Because I have added to set composite Key so.

Experiment experimentLocal = entityManager.find(Experiment.class, experiment);

primary key(labid, experiment_id)

Experiment experiment = new Experiment();
        experiment.setLabId(labId);
        experiment.setExperimentId(experimentId);

so primary Key is combination of two columns, so I wanted to soft delete the whole row based on primary key,

Thanks,
AjayKumar.

**Comment by kannuriajay** [comment]
Hi,

For  the below statement 
And to add clarify further as the key experiment table in your case is of composite type, so you need to create an embeddedId and perform search corresponding to the embeddedId object instead of complete experiment object. Sample entity class :

we are using : 

```
 @PartitionKey(0)
@Column(name = "labid")
private UUID labId;

@ClusteringColumn(0)
@Column(name = "experiment_id")
private UUID experimentId;
```

So we are not using embeddedId , how to resolve issue.

Thanks.
Ajaykumar

**Comment by chhavigangwal** [comment]
@kannuriajay 

Being a JPA compliant object mapper Kundera supports composite key by using @EmbeddedId annotation (https://docs.oracle.com/javaee/7/tutorial/doc/persistence-intro001.htm) . So in order to use Kundera , you need to declare the composite key of your class using @EmbeddedId annotation.  e.g : 

```
@Entity
public class Experiment
{
    @EmbeddedId
    private ExpKey key;
}


@Embeddable
public class ExpKey
{
   @Column(name = "labid")
     private UUID labId;

   @Column(name = "experiment_id")
    private UUID experimentId;
}
```

Chhavi

**Comment by kannuriajay** [comment]
It works .. thanks you
