### ISSUE TITLE
Strange Warnings (apache-cassandra-clientutil-2.1.3.jar and apache-cassandra-thrift-2.1.3.jar)

### ISSUE THREAD

**Issue by pluttrell** [Impetus/kundera#721]
I'm working on getting Kundera setup in a Wildfly 8.2 deployment.

I've added the following dependencies in my gradle script:

```
compile 'com.impetus.kundera.core:kundera-core:2.15.1'
compile 'com.impetus.kundera.client:kundera-cassandra:2.15.1'
compile 'com.impetus.kundera.client:kundera-cassandra-ds-driver:2.15.1'
```

And when I deploy the EAR, I get the following warnings:

```
Class Path entry apache-cassandra-clientutil-2.1.3.jar in /content/MyTest.ear/lib/cassandra-all-2.1.3.jar  does not point to a valid jar for a Class-Path reference.
Class Path entry apache-cassandra-thrift-2.1.3.jar in /content/MyTest.ear/lib/cassandra-all-2.1.3.jar  does not point to a valid jar for a Class-Path reference.
```

How do I resolve these?

Thanks.

**Comment by devender-yadav** [comment]
@pluttrell 

If you check MANIFEST.MF file under META-INF in `cassandra-all-2.1.3.jar` , you will find : 

```
Class-Path: apache-cassandra-clientutil-2.1.3.jar apache-cassandra-thrift-2.1.3.jar
```

which means that `cassandra-all-2.1.3.jar` refers classes in `apache-cassandra-clientutil-2.1.3.jar` and `apache-cassandra-thrift-2.1.3.jar`. When `cassandra-all-2.1.3.jar` loads it will also look for these references in the class-path in local network. These jars are not found in local network that's why these warnings are shown.

Since there is no need of these jars so you may ignore these warnings.

HTH,
Devender

**Comment by pluttrell** [comment]
@devender-yadav

Thanks for responding. 

Ya, I saw those `Class-Path` entries, and believe that these are usually automatically resolved by listing the dependences in the `.pom` file, which when Gradle builds the EAR, will usually include all sub-dependencies, which wasn't happening in this case. I took another look at it and it appears that one, but not both are included as dependencies `org.apache.cassandra:cassandra-all:2.1.3`, so it's a bit odd that this doesn't appear to be working.

In any event, great to know that these are not actually required/used by Kundera.
