### ISSUE TITLE
Accumulo  Support.

### ISSUE THREAD

**Issue by VanitySoft** [Impetus/kundera#77]
Would really like to see support for Accumulo. Are there any plans to add this? if so what is the time frame.  Thanks.

**Comment by xamry** [comment]
Support for Key-value pair database like Accumulo and many others (like Redis, Neo4J etc) are in various stages of consideration, but nothing has taken off yet.

We are working on making it easy for developers to create these support plug-ins and add to Kundera. In fact, this is how MongoDB support was added to Kundera.

If you are interested, and want to know more, please visit:
https://github.com/impetus-opensource/Kundera/wiki/Kundera%27s-Client-Extension-Framework

Regards,
Amresh

---

From: Reaper [reply@reply.github.com]
Sent: Monday, June 04, 2012 11:13 PM
To: Amresh Singh
Subject: [Kundera] Accumulo  Support. (#77)

Would really like to see support for Accumulo. Are there any plans to add this? if so what is the time frame.  Thanks.

---

Reply to this email directly or view it on GitHub:
https://github.com/impetus-opensource/Kundera/issues/77

---

Register for Impetus webinar ‘User Experience Design for iPad Applications’ June 8(10:00am PT). http://lf1.me/f9/

Impetus’ Head of Labs to present on ‘Integrating Big Data technologies in your IT portfolio’ at Cloud Expo, NY (June 11-14). Contact us for a complimentary pass.Impetus also sponsoring the Yahoo Summit 2012.

NOTE: This message may contain information that is confidential, proprietary, privileged or otherwise protected by law. The message is intended solely for the named addressee. If received in error, please destroy and notify the sender. Any use of this email is prohibited when received in error. Impetus does not represent, warrant and/or guarantee, that the integrity of this communication has been maintained nor that the communication is free of errors, virus, interception or interference.

**Comment by VanitySoft** [comment]
In other words 'no' , or  build it yourself. :)   ....I will take a crack at building an Accumulo plugin.
