### ISSUE TITLE
CassandraSchemaManager.java has hard coded port to initialize the client

### ISSUE THREAD

**Issue by amolc24** [Impetus/kundera#779]
CassandraSchemaManager.java line#671 method: initiateClient(). This is causing connection refused. Should this code use the port passed in, rather than hard coding ?

 if (host == null || !StringUtils.isNumeric(port) || port.isEmpty())
            {
                log.error("Host or port should not be null, Port should be numeric.");
                throw new IllegalArgumentException("Host or port should not be null, Port should be numeric.");
            }
            TSocket socket = new TSocket(host, Integer.parseInt("9160"));

**Comment by karthikprasad13** [comment]
@amolc24 

We have fixed the code and pushed it to the trunk. You can build the code from trunk for changes to be effective.

-Karthik

**Comment by amolc24** [comment]
Thanks Karthik. Any idea when would that fix be available on maven repository?

**Comment by karthikprasad13** [comment]
@amolc24 

The fix will be available with the next release, which is scheduled on 11th of September.

-Karthik

**Comment by chhavigangwal** [comment]
@amolc24 

In order to create schema using kundera-cassandra DSClient , you will need to specify the thrift (rpc_port) port over which it can connect with Cassandra :

You can do the same by setting :

```
  Map<String, Object> puPropertiesObj = new HashMap<String, Object>();
  puPropertiesObj.put(CassandraConstants.THRIFT_PORT, "9160");
  emf = Persistence.createEntityManagerFactory("ds_pu",puPropertiesObj);
```

If you do not specify this property while creating schema then default port 9160 will be picked as its thrift port in case DSClient and "kudera.port" property's value for Casssandra's  core client. Please find the test case below for your reference:

https://github.com/impetus-opensource/Kundera/blob/2503ad37db60abe195973d6c418ba186e702e74d/src/kundera-cassandra/cassandra-ds-driver/src/test/java/com/impetus/client/cassandra/crud/compositeType/association/CassandraUserOTMTest.java

Chhavi
