### ISSUE TITLE
com.impetus.kundera.persistence.event.EntityEventDispatcher is not getting Garbage collected

### ISSUE THREAD

**Issue by vinodjayachandran** [Impetus/kundera#825]
I am using Kundera as an ORM for cassandra. As part of our nightly job we try insert approximately 60k rows into cassandra daily. During the process if a row with PRIMARY key already exists (as may update primary key too), we do the following

```
Delete
Flush explicitly
Insert
Flush explicitly
```

Without calling Flush I noticed some inconsistency in final Total number of rows.

We end up in Heap out of memory as almost every second Full GC tries to happen. During this process as part of heap dump I found there are too many instances of 'com.impetus.kundera.persistence.event.EntityEventDispatcher'

**Comment by karthikprasad13** [comment]
@vinodjayachandran 

This is not exactly the issue with `com.impetus.kundera.persistence.event.EntityEventDispatcher`.

You should clear the `entityManager` after certain operations i.e. `em.clear()`

-Karthik

**Comment by vinod-bb** [comment]
@karthikprasad13 

Is Invoking em.clear() a work around ? 

IMO, it should be handled on it own. I don't explicitly create EntityEventDispatcher and there is no way I can deduce to clear entityManager for no reason at frequent intervals of time.

Is it documented anywhere which says on calling flush, entityManager should be cleared ?

**Comment by karthikprasad13** [comment]
@vinodjayachandran 

In JPA, doing `flush` will ensure that all the dirty objects attached to `EntityManager` are synchronized with the database. Objects remain attached to the `EntityManager` so that the updates could be bundled. 

Whereas, `clear` will detach all the objects from the `EntityManager`. So, IMHO for an application where frequent updates are not a case explicit `clear` should be called.

-Karthik

**Comment by chhavigangwal** [comment]
@vinodjayachandran 

Are we good to close on this ?

Chhavi

**Comment by vinodjayachandran** [comment]
Sure,

We can close it. I agree with Karthik.
