### ISSUE TITLE
BUG: Table is not created if column definition is not placed adjacent to field variable

### ISSUE THREAD

**Issue by jainman** [Impetus/kundera#84]
Hi I am using Kundera 206 ORM  to do CRUD operation on HBASE/HADOOP cluster.
Entity class is expecting the Column definition above  variable definition. Please look at the example below for explanation. 
Hibernate or ORM doesn't have this limitation.
# 

I am trying to create an Entity. But Entity is created without any Column family
NAME => 'LOGRECORD', FAMILIES => []}

After debugging  I found that entity class is expecting the Column definition is certain format

e.g. THIS Entity class definition  doesn't create any Column family --- Column definition  adjacent to getter
IDENTITY    {NAME => 'IDENTITY', FAMILIES => []}

@Entity
@Table(name = "IDENTITY", schema = "KunderaExamples@testhbase")
public class TestEntity {
    @Id
    private String id;

```
private String name;

public String getId() {
    return id;
}
public void setId(String id) {
    this.id = id;
}

@Column(name="name")
public String getName() {
    return name;
}
public void setName(String name) {
    this.name = name;
}
```

}

If the Class definition is written as below,  THIS Entity class definition  create all Column family ---
Column definition  adjacent to field variable

IDENTITY    {NAME => 'IDENTITY', FAMILIES => [{NAME => 'name', BLOOMFILTER => 'NONE', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '3', TTL => '2147483647', BLOCKSIZE => '65536', IN_MEMORY => 'false', BLOCKCACHE => 'true'}]}

@Entity
@Table(name = "IDENTITY", schema = "KunderaExamples@testhbase")
public class TestEntity {
    @Id
    private String id;

```
@Column(name="name")
private String name;

public String getId() {
    return id;
}

public void setId(String id) {
    this.id = id;
}

public String getName() {
    return name;
}

public void setName(String name) {
    this.name = name;
}
```

}

**Comment by mevivs** [comment]
Kundera does not support @Column support over methods as of now. It only supports over variable.

-Vivek

**Comment by mevivs** [comment]
Marking it as a candidate for 2.0.8 release

**Comment by xamry** [comment]
We are aware of this issue. Currently we are reading @Column annotation from field definition only. We intend to fix this, meanwhile, you can get this working by annotating fields.

Sent from Samsung Mobile

jainman reply@reply.github.com wrote:
Hi I am using Kundera 206 ORM  to do CRUD operation on HBASE/HADOOP cluster.
Entity class is expecting the Column definition above  variable definition. Please look at the example below for explanation.
Hibernate or ORM doesn't have this limitation.

# 

I am trying to create an Entity. But Entity is created without any Column family
NAME => 'LOGRECORD', FAMILIES => []}

After debugging  I found that entity class is expecting the Column definition is certain format

e.g. THIS Entity class definition  doesn't create any Column family ---
IDENTITY        {NAME => 'IDENTITY', FAMILIES => []}

@Entity
@Table(name = "IDENTITY", schema = "KunderaExamples@testhbase")
public class TestEntity {
        @Id
    private String id;

```
private String name;

public String getId() {
            return id;
    }
    public void setId(String id) {
            this.id = id;
    }

@Column(name="name")
public String getName() {
            return name;
    }
    public void setName(String name) {
            this.name = name;
    }
```

}

If the Class definition is written as below,  THIS Entity class definition  doesn't create any Column family ---

IDENTITY        {NAME => 'IDENTITY', FAMILIES => [{NAME => 'name', BLOOMFILTER => 'NONE', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '3', TTL => '2147483647', BLOCKSIZE => '65536', IN_MEMORY => 'false', BLOCKCACHE => 'true'}]}

@Entity
@Table(name = "IDENTITY", schema = "KunderaExamples@testhbase")
public class TestEntity {
        @Id
    private String id;

```
@Column(name="name")
private String name;

public String getId() {
            return id;
    }

    public void setId(String id) {
            this.id = id;
    }

    public String getName() {
            return name;
    }

    public void setName(String name) {
            this.name = name;
    }
```

}

---

Reply to this email directly or view it on GitHub:
https://github.com/impetus-opensource/Kundera/issues/84

---

View Impetus webcast 'User Experience Design for iPad Applications' http://lf1.me/U8/ .

Impetus to showcase 'Accelerated services for Big Data' using in-built IPs: Ankush - First vendor agnostic Big Data Cluster Manager and Jumbune - First Map Reduce Profiler at Hadoop Summit 2012, CA; June 13-14

NOTE: This message may contain information that is confidential, proprietary, privileged or otherwise protected by law. The message is intended solely for the named addressee. If received in error, please destroy and notify the sender. Any use of this email is prohibited when received in error. Impetus does not represent, warrant and/or guarantee, that the integrity of this communication has been maintained nor that the communication is free of errors, virus, interception or interference.

**Comment by mevivs** [comment]
Marking it as a candidate for 2.0.8 release, as not very critical.

**Comment by mevivs** [comment]
HBase schema handling is changed. So should not be issue anymore.
