### ISSUE TITLE
elasticsearch pagination support

### ISSUE THREAD

**Issue by dreamingo88** [Impetus/kundera#841]
i create a demo project with kundera 3.3 today (use elasticsearch 1.7 to persist my data).
but elasticsearch doesn'e support pagination. 
`
Query q = em.createQuery("select ctg from Category ctg where ctg.code = 'abc'", Category.class);
int startPos = page * 10;
q.setFirstResult(startPos);
q.setMaxResults(10);
List<Category> ctg = q.getResultList();
`
it always returns the same list.
please implement it, it's very important. thanks.

**Comment by karthikprasad13** [comment]
@dreamingo88 

We will take it up in the future releases.

-Karthik

**Comment by dreamingo88** [comment]
@karthikprasad13 
good news.
thanks!

**Comment by dreamingo88** [comment]
Is there any news about this feature?
Will it be implement in 3.5?

**Comment by devender-yadav** [comment]
@dreamingo88 

We were planning to finish this task in 3.5 release (_expected to be released in 2 weeks_). But due to other tasks and priority, we probably will not be able to complete this in 3.5 release. 

It would be great if you add this feature to Kundera-Elasticsearch. Kundera team will help you if you need any understanding or discussion for that. Otherwise, we will pick this task in Kundera 3.6 release (_expected to be released in mid August_)

-Dev

**Comment by devender-yadav** [comment]
@dreamingo88 

Fix has been added to the trunk. It will be available in Kundera 3.6 (_expected to be released in mid September_)

-Dev
