### ISSUE TITLE
Aggregate functions are not supported in Kundera

### ISSUE THREAD

**Issue by AntonYudin** [Impetus/kundera#982]
I'm using cassandra 3.11.0 and it looks that aggregate functions are not supported.
A simple query like:
`SELECT MAX(field) FROM Table t WHERE id = :value`
is translated to CQL by kundera as
`SELECT * FROM "Table" WHERE "id" = value`
and `getSingleResult()` returns an Entity object instead of a field.

Are there any plans to add support for standard aggregate functions?

**Comment by karthikprasad13** [comment]
Hi @AntonYudin 

Aggregate queries are not yet supported since there is no native support for aggregations in many NoSQL databases supported by Kundera.

As a workaround, you can use `createNativeQuery` for running aggregations in Cassandra.

Check this [testcase](https://github.com/impetus-opensource/Kundera/blob/cc72b8da254c5bcb9b2caf870cee0b4a9cc0fbfb/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/crud/CassandraNativeFunctionsTest.java#L92) for more info 

-Karthik

**Comment by AntonYudin** [comment]
Thanks for the reply.

It would work if kundera supported setting parameters on native queries.
According to this [issue](https://github.com/impetus-opensource/Kundera/issues/508) and my own tests, setting parameters on native queries is not supported.

Thanks.

**Comment by devender-yadav** [comment]
Reference - https://github.com/Impetus/Kundera/pull/983
