### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: com.impetus.kundera.persistence.AbstractEntityReader: method <init>()V not found

### ISSUE THREAD

**Issue by mayankqait** [Impetus/kundera#988]
Exception in thread "main" java.lang.NoSuchMethodError: com.impetus.kundera.persistence.AbstractEntityReader: method <init>()V not found
	at com.impetus.client.rdbms.query.RDBMSEntityReader.<init>(RDBMSEntityReader.java:103)
	at com.impetus.client.rdbms.RDBMSClientFactory.initialize(RDBMSClientFactory.java:77)
	at com.impetus.kundera.loader.GenericClientFactory.load(GenericClientFactory.java:115)
	at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:55)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:408)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:161)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:135)
	at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:39)
	at com.example.demo.KunderaSpringSampleApplication.main(KunderaSpringSampleApplication.java:48)

**Comment by devender-yadav** [comment]
Hi @mayankqait,

Please share Kundera version, database name & version and code specific to this exception.

**Comment by mayankqait** [comment]
pom.xml


<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.infotech</groupId>
	<artifactId>KunderaSpringSample</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>KunderaSpringSample</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.9.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
         <dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>4.3.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-cassandra</artifactId>      
        </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		 <dependency>
          <groupId>com.impetus.kundera.client</groupId>
          <artifactId>kundera-cassandra</artifactId>
          <version>3.3</version>
       </dependency> 
       
      
       <dependency>
         <groupId>com.impetus.client</groupId>
          <artifactId>kundera-rdbms</artifactId>
         <version>2.8.1</version>
      </dependency>
      
      <dependency>
        <groupId>com.impetus.core</groupId>
        <artifactId>kundera-core</artifactId>
        <version>2.9</version>
      </dependency>
      
      <dependency>
          <groupId>com.impetus.kundera.client</groupId>
          <artifactId>data-as-object</artifactId>
          <version>3.12</version>
       </dependency> 
	</dependencies>
    
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>


</project>



<persistence xmlns="http://java.sun.com/xml/ns/persistence"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
	https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd"
	version="2.0">
 <persistence-unit name="mysqlPU">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    
    <class>com.infotech.model.User</class>
    <properties>
      <property name="kundera.client.lookup.class" value="com.impetus.client.rdbms.RDBMSClientFactory" />
      <property name="hibernate.show_sql" value="true" />
      <property name="hibernate.format_sql" value="true" />
      <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect" />
      <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver" />
      <property name="hibernate.connection.url" value="jdbc:mysql://localhost:3306/employeeCombo" />
      <property name="hibernate.connection.username" value="root" />
      <property name="hibernate.connection.password" value="root" />
      <property name="hibernate.current_session_context_class" value="org.hibernate.context.ThreadLocalSessionContext" />
    </properties>
</persistence-unit> 

 <persistence-unit name="cassandrapu">
		<provider>com.impetus.kundera.KunderaPersistence</provider>
    	
		<class>com.infotech.model.User</class>
		<class>com.impetus.kundera.datakeeper.entities.SubordinatesCounter</class>
		<exclude-unlisted-classes>true</exclude-unlisted-classes>
		<properties>
			<property name="kundera.nodes" value="localhost" />
			<property name="kundera.port" value="9042" />
			<property name="kundera.keyspace" value="employeecombo" />
			 <property name="kundera.ddl.auto.prepare" value="create" />
			 <property name="kundera.dialect" value="cassandra"/>
			<property name="kundera.client" value="thrift" />
			<property name="kundera.client.lookup.class"
				value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
		</properties>
	</persistence-unit> 
	
	
</persistence> 


for cassandra [cqlsh 5.0.1 | Cassandra 2.2.11 | CQL spec 3.3.1 | Native protocol v4]
for mysql  mysql  Ver 14.14 Distrib 5.7.21

**Comment by mayankqait** [comment]
package com.example.demo;

import java.util.HashMap;
import java.util.Map;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.PersistenceUnit;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

import com.impetus.client.cassandra.common.CassandraConstants;
import com.impetus.kundera.KunderaPersistence;
import com.impetus.kundera.persistence.EntityManagerFactoryImpl;
import com.infotech.model.User;
//@PersistenceUnit
@EntityScan("com.infotech.model")
@ComponentScan(basePackages="com.infotech")
//@EnableCassandraRepositories("com.infotech.cassRepo")
@EnableJpaRepositories("com.infotech.repository")
@Configuration
@EnableAutoConfiguration
@SpringBootApplication
public class KunderaSpringSampleApplication {
    
	//@PersistenceContext(unitName = "mysqlPU", type = PersistenceContextType.EXTENDED)
    //private static EntityManager emf;
	@Autowired
	static KunderaPersistence kp;
	
	public static void main(String[] args) {
		User user = new User();
        user.setUserId(1);
        user.setFirstName("ram");
        user.setLastName("gopal");
        user.setCity("Noida");
        
        
        //enable CQL3
       /*Map<String, String> props = new HashMap<>();
        props.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_2_0);*/
       //EntityManagerFactoryImpl emf = (EntityManagerFactoryImpl) kp.createEntityManagerFactory("mysqlPU", null);
       EntityManagerFactory emf = Persistence.createEntityManagerFactory("mysqlPU");
       EntityManager em = emf.createEntityManager();
        
        em.persist(user);
        em.close();    
        emf.close();
		SpringApplication.run(KunderaSpringSampleApplication.class, args);
								
	}
}

**Comment by karthikprasad13** [comment]
@mayankqait 

This could be a dependency issue. You are using `kundera-cassandra version: 3.3`, `kundera-rdbms version: 2.8.1`, `kundera-core version: 2.9` and `data-as-object version 3.12`. Please check if core modules of these versions are not in conflict.

I suggest you to use kundera-3.12 (latest as of now) which is compatible with latest version of Cassandra. If you want to use Cassandra version 2.2.11, you can use kundera-3.4 (compatible with Cassandra 2+)

-Karthik

**Comment by PandaMonkey** [comment]
@mayankqait I agree that this problem is caused by dependency version conflicts on classpath. The root cause is that class "com.impetus.kundera.persistence.AbstractEntityReader" exists in two JARs:
class_version1 exist in com.impetus.core:kundera-core:2.9,
and class_version2 exist in com.impetus.kundera.core:kundera-core:3.3(imported through com.impetus.kundera.client:kundera-cassandra:3.3).
However, the method <init>() only defined in class_version1. Unfortunately, by analyzing your pom.xml, JVM actually loads class_version1 at runtime, so that java.lang.NoSuchMethodError was thrown.

You can add the following patch to work around this problem. 

		<dependency>
			<groupId>com.impetus.kundera.core</groupId>
			<artifactId>kundera-core</artifactId>
			<version>2.9.1</version>
		</dependency>
		
Hope this can help you. ^_^

**Comment by PandaMonkey** [comment]
@mayankqait I agree that this problem is caused by dependency version conflicts on classpath. The root cause is that class "com.impetus.kundera.persistence.AbstractEntityReader" exists in two JARs:
class_version1 exist in com.impetus.core:kundera-core:2.9,
and class_version2 exist in com.impetus.kundera.core:kundera-core:3.3(imported through com.impetus.kundera.client:kundera-cassandra:3.3).
However, the method <init>() V only defined in class_version1. Unfortunately, by analyzing your pom.xml, JVM actually loads class_version2 at runtime, so that java.lang.NoSuchMethodError was thrown.

You can add the following patch to work around this problem.

	<dependency>
		<groupId>com.impetus.kundera.core</groupId>
		<artifactId>kundera-core</artifactId>
		<version>2.9.1</version>
	</dependency>
Hope this can help you. ^_^

**Comment by PandaMonkey** [comment]
@mayankqait I agree that this problem is caused by dependency version conflicts on classpath. The root cause is that class "com.impetus.kundera.persistence.AbstractEntityReader" exists in two JARs:
class_version1 exist in com.impetus.core:kundera-core:2.9,
and class_version2 exist in com.impetus.kundera.core:kundera-core:3.3(imported through com.impetus.kundera.client:kundera-cassandra:3.3).
However, the method init () V only defined in class_version1. Unfortunately, by analyzing your pom.xml, JVM actually loads class_version2 at runtime, so that java.lang.NoSuchMethodError was thrown.

You can add the following patch to work around this problem.

<dependency>
	<groupId>com.impetus.kundera.core</groupId>
	<artifactId>kundera-core</artifactId>
	<version>2.9.1</version>
</dependency>
Hope this can help you. ^_^

**Comment by PandaMonkey** [comment]
@mayankqait I agree that this problem is caused by dependency version conflicts on classpath. The root cause is that class "com.impetus.kundera.persistence.AbstractEntityReader" exists in two JARs:
class_version1 exist in com.impetus.core:kundera-core:2.9,
and class_version2 exist in com.impetus.kundera.core:kundera-core:3.3(imported through com.impetus.kundera.client:kundera-cassandra:3.3).
However, the method init() V only defined in class_version1. Unfortunately, by analyzing your pom.xml, JVM actually loads class_version2 at runtime, so that java.lang.NoSuchMethodError was thrown.

You can add the following patch to work around this problem.

<dependency>
	<groupId>com.impetus.kundera.core</groupId>
	<artifactId>kundera-core</artifactId>
	<version>2.9.1</version>
</dependency>
Hope this can help you. ^_^

**Comment by PandaMonkey** [comment]
@mayankqait I agree that this problem was caused by dependency version conflict on classpath. The root cause is that class "com.impetus.kundera.persistence.AbstractEntityReader" exists in two JARs:
class_version1 exist in com.impetus.core:kundera-core:2.9,
and class_version2 exist in com.impetus.kundera.core:kundera-core:3.3(imported through com.impetus.kundera.client:kundera-cassandra:3.3).
However, the method init () V is only defined in class_version1. Unfortunately, by analyzing your pom.xml, JVM actually loaded class_version2 at runtime, so that java.lang.NoSuchMethodError was thrown.

You can add the following patch to work around this problem.

<dependency>
	<groupId>com.impetus.kundera.core</groupId>
	<artifactId>kundera-core</artifactId>
	<version>2.9.1</version>
</dependency>
Hope this can help you. ^_^

**Comment by PandaMonkey** [comment]
@mayankqait I agree that this problem was caused by dependency version conflict on classpath. The root cause is that class "com.impetus.kundera.persistence.AbstractEntityReader" exists in two JARs:
class_version1 exist in com.impetus.core:kundera-core:2.9,
and class_version2 exist in com.impetus.kundera.core:kundera-core:3.3(imported through com.impetus.kundera.client:kundera-cassandra:3.3).
However, the method init () V is only defined in class_version1. Unfortunately, by analyzing your pom.xml, JVM actually loaded class_version2 at runtime, so that java.lang.NoSuchMethodError was thrown.

You can add the following patch to work around this problem.

<dependency>
	<groupId>com.impetus.kundera.core</groupId>
	<artifactId>kundera-core</artifactId>
	<version>2.9.1</version>
</dependency>

Hope this can help you. ^_^

**Comment by PandaMonkey** [comment]
Patch:

<dependency>
	<groupId>com.impetus.kundera.core</groupId>
	<artifactId>kundera-core</artifactId>
	<version>2.9.1</version>
</dependency>

**Comment by PandaMonkey** [comment]
@mayankqait I agree that this problem was caused by dependency version conflict on classpath. The root cause is that class "com.impetus.kundera.persistence.AbstractEntityReader" exists in two JARs:
class_version1 exist in com.impetus.core:kundera-core:2.9,
and class_version2 exist in com.impetus.kundera.core:kundera-core:3.3(transitivity introduced by com.impetus.kundera.client:kundera-cassandra:3.3).
However, the method init () V is only defined in class_version1. Unfortunately, by analyzing your pom.xml, JVM actually loaded class_version2 at runtime, so that java.lang.NoSuchMethodError was thrown.

You can add the following patch to work around this problem.
Hope this can help you. ^_^
[patch.TXT](https://github.com/Impetus/Kundera/files/1713204/patch.TXT)
